defaults:
  domain: 'gallery.dev'
  mail_from: 'katie@khouck.com'
  s3:
    access_key_id: AKIAILRF4EOSNYCDBE5A
    secret_access_key: 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
    bucket: 'khouck-photos-dev'
    zip_bucket: 'khouck-orders-dev'
  contact_email: 'katie@khouck.com'
  paypal:
    email:     'seller_1343845258_biz@gmail.com'
    password:  '343847027'
    pdt_token: 'auqBVoSfcLsWiLp6C_WVYPzqZ8587uje3agL1NVtjJq-Xlmlz8SvyQ0KOx8'
    endpoint:  'https://www.sandbox.paypal.com/cgi-bin/webscr'

development:
  foo: bar

test:
  foo: bar

production:
  domain: 'www.khouck.com'
  paypal:
    email:     'katie@khouck.com'
    password:  ''
    pdt_token: 'RdBopUKIniNojuUAjZro8EUNL6PhwBgH7Mj4JpADqXVOHt2Qsu_q1OFaCcm'
    endpoint:  'https://www.paypal.com/cgi-bin/webscr'
  s3:
    bucket: 'khouck-photos'
    zip_bucket: 'khouck-orders'
